### ISSUE TITLE
etc/rt/cn_test.rt - glitch & etc/rt/cat.rt - disappear

### ISSUE THREAD

**Issue by 42ghan** [brilliantshell/miniRT#98]
이슈 남겨둡니다...

1. `etc/rt/cn_test.rt` 지지직지직
![Screen Shot 2021-12-21 at 1 18 16 AM](https://user-images.githubusercontent.com/83805691/146799498-4ca67c34-d149-4bd6-b80a-6313d663536f.png)
 
2. `etc/rt/cat.rt` 있어야 하는데 없는데 있습니다 🙃 회전해야 보입니다...
https://user-images.githubusercontent.com/83805691/146799669-5d31ce5d-1cd5-4d0f-b767-b87dc06d7491.mov

**Comment by yongjulejule** [comment]
저 지직지직에 +-0.1 이런 방식이 예전부터 근본적인 문제가 있다고 생각하긴 했는데 함 고쳐보겠습니다 ㅎㅎㅎ

**Comment by 42ghan** [comment]
@yongjulejule cat.rt는 문제가 아닌 것 같네요
```
A .2 50,50,50
C 0,0,500 -1,0,0 70
L 600,0,0 .7 255,255,255
sp 0,0,0 200 255,255,255
sp 0,0,200 10 255,0,0
tx cat.ppm 0
```
카메라 o_vect 보니까 회전이 돼야지만 보이는게 맞겠네요 하하... 그냥 고양이는 평가자한테 안 보여주는 걸로 ;)

**Comment by yongjulejule** [comment]
@42ghan 아 그리고 회전시키면 애들이 순간이동 하는 문제 있자나여? 그게 문제 있는게 아니라 카메라를 회전시키면 원점을 보면서 구형으로 이동하게 된단 말이져? 따라서 다 정상입니다. 이게 기준점이 없으면 구형으로 움직일 수 가 없어서 제가 기준점을 원점으로 잡고 카메라를 회전시켰는데 맨날 카메라 o_vect를 원점으로 잡다 보니 생각을 못하고 있었네욤
